config/routes.rb
MyRemainder::Application.routes.draw do

  resources :characters

  resources :tasks do
    resources :reminders
  end
  
  root :to => 'home#index'

  match "remainders/new/:id"=>"remainder#new"
  match "tasks/logout"=>"tasks#logout"
  match "tasks/selesai_task/:id"=>"tasks#selesai_task"
  match "tasks/belum_task/:id"=>"tasks#belum_task"

  #all get
  get "home/index"
  get "home/daftar_member"
  get "home/gagal_login"
  get "home/:id" => "home#cek_login"
  get "home2/index"


  #all post
  post "home/cek_login"=>"home#cek_login"
  post "home/gagal_login"=>"home#gagal_login"
 
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible  :judul_task, :kategori, :ket_task, :status, :tempat_task, :tgl_task   ,:department  ,:id_user,:latitude, :longitude ,:gmaps
      validates_presence_of :judul_task,:tgl_task,:status, :tempat_task
      
    has_many :reminder,:dependent => :destroy
#      validates_uniqueness_of :email_user



  def self.search(search,departemen)
    if search
      find(:all, :conditions => ['department LIKE ? and (tempat_task LIKE ? or kategori LIKE ? or judul_task LIKE ? or ket_task LIKE ? )',"#{departemen}","%#{search}%","%#{search}%", "%#{search}%","%#{search}%"],:order=>'status asc, tgl_task desc')
    else
      find(:all ,:conditions => ['department LIKE ? )',"#{departemen}"],:order=>'status asc, tgl_task desc')
    end
  end

  acts_as_gmappable
  def gmaps4rails_address
    tempat_task
  end
  def gmaps4rails_infowindow
    judul_task
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :authorize


  def index
    if session[:welcomedialog]!= false
       session[:welcomedialog]= true
    end
    @user=User.find(session[:user_id])
    @departemen=@user.department

    if params[:search]
      @tasks = Task.search(params[:search],@departemen)
    else
      @tasks = Task.all(:conditions=>{:department=>@departemen},:order=>'status asc, tgl_task desc')
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  def logout
    @user=User.find(session[:user_id])
    @user.update_attribute(:updated_at,Time.now.strftime('%Y-%m-%d %H:%M:%S'))
    session[:welcomedialog]= true
    flash[:notice] = "Anda sudah logout"
    redirect_to(:controller => :home, :action => :index)
  end  

  
  # GET /tasks/1
  # GET /tasks/1.json
  def show

    @json = Task.find(params[:id]).to_gmaps4rails
    @task = Task.find(params[:id]) 
    if(params[:section])
      @section=params[:section]
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    @setStatus=[['Belum Selesai']]
    @statusValue="Belum Selesai"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  
  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    @setStatus=[['Belum Selesai'],['Selesai']]
    @statusValue=@task.status
    @task.update_attribute(:gmaps,0)
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    @setStatus=[['Belum Selesai']]
    @statusValue=@task.status
    @user=User.find(session[:user_id])
    @task.department= @user.department
    @task.email_user = @user.email
    @task.id_user=@user.id
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def belum_task
  @task = Task.find(params[:id])
  @task.update_attribute(:status,'Belum Selesai')
  redirect_to :action=>:index
  end
  
  
  def selesai_task
  @task = Task.find(params[:id])
  @task.update_attribute(:status,'Selesai')
  redirect_to :action=>:index
  end
  
  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def ganti_nama_hari(hari)
    if hari=='0'
      hari='Minggu'
    elsif hari =='1'
      hari='Senin'
    elsif hari =='2'
      hari='Selasa'
    elsif hari =='3'
      hari='Rabu'
    elsif hari =='4'
      hari='Kamis'
    elsif hari =='5'
      hari='Jumat'
    elsif hari =='6'
      hari='Sabtu'
    end

    end
end

app/views/tasks/_form.html.erb
<script>
    $(function() {
        $('.datepicker').datetimepicker({timeFormat: "hh:mm:ss",dateFormat:'yy-mm-d'});
    });
</script>

<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table cellspacing="10">
  <tr valign="top">
    <td>
      <div class="field">
        <%= f.label :judul_task ,"Judul Kegiatan" %><br />
        <%= f.text_field :judul_task ,:size=>50%>
      </div>
      <div class="field">
        <%= f.label :tgl_task,"Tanggal Kegiatan" %><br />
        <!--<%= f.datetime_select :tgl_task %>-->
        <%= f.text_field :tgl_task,:class => 'datepicker'%>
      </div>

      <div class="field">
        <%= f.label :kategori,"Kategori" %><br />
        <%= f.select :kategori,Category.all.collect {|p| [ p.name] }%>
      </div>
      <div class="field">
        <%= f.label :tempat_task ,"Tempat Kegiatan"%><br />

        <%= f.text_area :tempat_task,:rows=>4 %> <br />
        NB:Masukan kota pada line pertama untuk melihat google map.<br />
      </div>
      
    </td>
    <td>
      <div class="field">
        <%= f.label :status,"Status" %><br />
        <%= f.select(:status,options_for_select(@setStatus,:selected=>@statusValue))%>
      </div>
      <div class="field" >
        <%= f.label :ket_task ,"Catatan Kegiatan"%><br />
        <%= f.text_area :ket_task %>
      </div>      
    </td>
  </tr>
  <tr>
    <td>
  <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
   </td>   
   </tr>
</table>
  
  

app/views/tasks/edit.html.erb
<h1>Edit Kegiatan</h1>

<%= render 'form' %>

<%= link_to 'Detail', @task %> |
<%= link_to 'Kembali', tasks_path %>

app/views/tasks/index.html.erb
<script type="text/javascript">
            function showTime(){
                    var timeNow = new Date(); 
                    document.getElementById('spHrs').innerHTML = timeNow.getHours();
                    document.getElementById('spMins').innerHTML = timeNow.getMinutes();
                    document.getElementById('spSecs').innerHTML = timeNow.getSeconds();
            }
            setInterval(showTime,1000);
</script>

<center><h1 id="JudulPage">Task List / Daftar Kegiatan Departement <%= h(@user.department).upcase  %></h1></center>
<% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:error] %>
    <p id="error"><%= flash[:error] %></p>
<% end %>


<div  align=right>
  <%= form_tag tasks_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search],:size=>40 %>
        <%= submit_tag "Search", :judul_task => nil %>
      </p>
  <% end %>

</div>

  <!--<%link_to(image_tag("/images/search.png"),{:style =>"vertical-align:top" }) %>-->


<table>
  <tr valign="top" >
      <td width="200px" align="center">
        
        Selamat Datang: <br/>
        <%= h(@user.nama).upcase %><br/>
        Departement :
        <%= h(@user.department).upcase %><br/>
        <br/>
        Login terakhir : <%= @user.updated_at.strftime(" %d-%B-%Y ") %><br/><br/>
        Sekarang : <%= Time.now.strftime(" %d-%B-%Y")  %><br/>
        <div id="clockContainer">
            <span id="spHrs"></span> : <span id="spMins"></span> : <span id="spSecs"></span>
        </div>

        <br/>

        <%= button_to 'Kegiatan Baru',{ :action => :new}, {:method => :get,:class=>"LoginSubmit "} %>    <br>
        <%= button_to 'Logout',{:action => :logout},:class=>"LoginSubmit" %>
        <br/><br/>       
        
        <br/>
         
      </td>
      <td width="100%" border="0" >
       
        <table id="my_table" cellpadding="5" cellspacing="0">
          <thead> 
        <tr>
          <th> Aksi</th>
          <th> Judul</th>
          <th> Waktu </th>
          <th> Tempat</th>
          <th> Status</th>
          <th> Reminder</th>
          <th> PIC </th>
        </tr>
        </thead>
        <tbody>
        <% odd_or_even = 0
        for product in @tasks
          if(h(product.status)=='Selesai')
            odd_or_even=1
          else odd_or_even=0
          end
        %>
        <tr valign="top" class="ListLine<%= odd_or_even %>">
            <td class="ListActions" width="60px">
            <% if product.id_user == @user.id %>
            <%= link_to 'Detail', :action => 'show', :id => product %><br/>
            <%= link_to 'Edit Task', :action => 'edit', :id => product %><br/>
            <%= link_to 'Hapus',{ :action => 'destroy', :id => product },:method=>'delete',
              :confirm => "Anda yakin ingin menghapus task ini?" %><br/>
            <%if (h(product.status)!='Selesai')%>
            <%= link_to 'Selesai',{:action=>:selesai_task,:id=>product}%>
            <%else%>
            <%= link_to 'Belum Selesai',{:action=>:belum_task,:id=>product} %>
            <%end%>
            <% end %>
            </td>

            <td width="60%">
            <span class="ListTitle"><%= truncate(h(product.judul_task),:length=>80) %></span><br />
            <%= truncate(product.ket_task ,:length =>150) %>
            </td>

            <td><strong><%= product.tgl_task.strftime("%d-%b-%Y") %><br/>
            <%= ganti_nama_hari(product.tgl_task.strftime("%w")) %></strong>
            </td>

            <td  width="15%"><%= truncate(h(product.tempat_task),:length=>60) %>
            </td>

            <td align="right" width="18%">
            Kategori :<%= h(product.kategori) %><br/>
            Status :<strong><%= h(product.status)%></strong>
            </td>
            <td align="Center" width="15%">
              <% if product.id_user == @user.id %>
                <% ada_remainder=Reminder.where(:task_id =>product) %>
                <%if h(product.status)=='Selesai'%>
                Status selesai tidak lagi direminder
                <% elsif ada_remainder.blank?%>
                <%=link_to image_tag( '/images/reminder.png',:width=>"40"), :action=>'show',:id=>product,:section=>"1"%><br/>
                <%=link_to 'Set Reminder', :action=>'show',:id=>product,:section=>"1"%><br/>
                <%else %>
                  <% for ada in ada_remainder %>
                  Diset:<%= ada.waktu_reminder.strftime("%d-%b-%Y")  %><br/> Pukul:<%= ada.waktu_reminder.strftime("%T %p")%><br/>
                  <%= ada.occurance %><br/>
                      email akan dikirim ke: <%= product.email_user%>
                      <br/>
                  <%end%>
                <%end%>
              <%end%>

            </td>

            <td>
            <% if (product.id_user)%>

             <%= User.where({:id=>product.id_user} ).first.nama.upcase %>
             <% end %>
            </td>
        </tr>
        <% end %>
        </tbody>
        </table>
         <div><%=  render :partial => '/tasks/shared/tablesorter_pager' %></div>
      </td>
  </tr>
</table>

<!--ini untuk welcome dialog  if session[:welcomedialog] -->
<% if true %>
    <% @deliver=Delivered.joins("left join tasks on tasks.id=delivereds.task_id
    left join reminders on reminders.id= delivereds.reminder_id
    left join users on tasks.id_user=users.id where tasks.id_user=#{@user.id} and delivereds.lastdelivered > users.updated_at").
            select("distinct tasks.judul_task,reminders.occurance,delivereds.lastdelivered  ") %>
    <% if !@deliver.blank? %>
<script>
    // Untuk test dialog jquery
    $.fx.speeds._default = 1000;
    $(function() {
        $( "#dialog" ).dialog({
            autoOpen: true,
            show: "clip",
            hide: "fade" ,
            width:"auto" ,
            position:({
                my: 'left',
                at: 'right bottom'
            })
        });

        $( "#dialog" ).dialog( "open" );

        $("#myButton").click( function() {
            $("#dialog").dialog('close');
            <% session[:welcomedialog]=false %>
        });

    });
</script>

<div id="dialog" class="position1" title="Reminder Terkirim">
  <table>
    <tr >
      <th class=Listjquery>
        Reminder
      </th >
      <th class=Listjquery>Pengulangan</th>
      <th class=Listjquery>Terakhir dikirim</th>
    </tr>

     <% for deliver in @deliver %>
        <tr>
          <td> <%= deliver.judul_task %></td>
          <td><%= deliver.occurance %></td>
          <td><%= deliver.lastdelivered.strftime("%d-%b-%Y %H:%M:%S") %></td>
        </tr>
      <%end%>
  </table>
  <button type="button" id="myButton" style="text-align: center;">Close</button>
</div>

<% end %>
<%end%>
<!-- akhir untuk welcome dialog-->

app/views/tasks/new.html.erb
<h1>Kegiatan Baru</h1>

<%= render 'form' %>

<%= link_to 'Kembali', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %><br/></p>
<%= link_to 'Edit Task', edit_task_path(@task) %> |
<%= link_to 'Main Menu List', tasks_path %>

<table width=100%>
  <tr >
    <td ALIGN=LEFT >
    <h2>Detail Task</h2>
    <p>
      <b>Judul task :</b>
      <%= @task.judul_task %>
    </p>

    <p>
      <b>Tanggal task :</b>
      <%= ganti_nama_hari(@task.tgl_task.strftime("%w"))+ @task.tgl_task.strftime(", %d %B %Y") %>
    </p>

    <p>
      <b>Pukul task :</b>
      <%= @task.tgl_task.strftime("%r") %>
    </p>

    <p>
      <b>Tempat task :</b>
      <%= @task.tempat_task %>
    </p>

    <p>
      <b>Ket task :</b>
      <%= @task.ket_task %>
    </p>

    <p>
      <b>Status :</b>
      <%= @task.status %>
    </p>

    <p>
      <b>Kategori :</b>
      <%= @task.kategori %>
    </p>
    </td>
    <td width="70%">

      <%= gmaps4rails(@json) %>

    </td>
  </tr>
</table>
<%#*untuk menampilkan partial page reminder%>
<div id="section1">
<%= render :partial=>"/tasks/reminder/reminder"%>
</div>

<%#*untuk set scrool page edit reminder%>
<%if @section%>
<script type="text/javascript">
// <!--
document.location.hash="section<%=@section %>";
// -->
</script>
<%end %>
|
<%= link_to 'Kembali ke Task List', tasks_path %>